export const industries = [
    { label: 'Accounting' },
    { label: 'Airlines / Aviation' },
    { label: 'Alternative Dispute Resolution' },
    { label: 'Alternative Medicine' },
    { label: 'Animation' },
    { label: 'Apparel / Fashion' },
    { label: 'Architecture / Planning' },
    { label: 'Arts / Crafts' },
    { label: 'Automotive' },
    { label: 'Aviation / Aerospace' },
    { label: 'Banking / Mortgage' },
    { label: 'Biotechnology / Greentech' },
    { label: 'Broadcast Media' },
    { label: 'Building Materials' },
    { label: 'Business Supplies / Equipment' },
    { label: 'Capital Markets / Hedge Fund / Private Equity' },
    { label: 'Chemicals' },
    { label: 'Civic / Social Organization' },
    { label: 'Civil Engineering' },
    { label: 'Commercial Real Estate' },
    { label: 'Computer Games' },
    { label: 'Computer Hardware' },
    { label: 'Computer Networking' },
    { label: 'Computer Software / Engineering' },
    { label: 'Computer / Network Security' },
    { label: 'Construction' },
    { label: 'Consumer Electronics' },
    { label: 'Consumer Goods' },
    { label: 'Consumer Services' },
    { label: 'Cosmetics' },
    { label: 'Dairy' },
    { label: 'Defense / Space' },
    { label: 'Design' },
    { label: 'E - Learning' },
    { label: 'Education Management' },
    { label: 'Electrical / Electronic Manufacturing' },
    { label: 'Entertainment / Movie Production' },
    { label: 'Environmental Services' },
    { label: 'Events Services' },
    { label: 'Executive Office' },
    { label: 'Facilities Services' },
    { label: 'Farming' },
    { label: 'Financial Services' },
    { label: 'Fine Art' },
    { label: 'Fishery' },
    { label: 'Food Production' },
    { label: 'Food / Beverages' },
    { label: 'Fundraising' },
    { label: 'Furniture' },
    { label: 'Gambling / Casinos' },
    { label: 'Glass / Ceramics / Concrete' },
    { label: 'Government Administration' },
    { label: 'Government Relations' },
    { label: 'Graphic Design / Web Design' },
    { label: 'Health / Fitness' },
    { label: 'Higher Education / Acadamia' },
    { label: 'Hospital / Health Care' },
    { label: 'Hospitality' },
    { label: 'Human Resources / HR' },
    { label: 'Import / Export' },
    { label: 'Individual / Family Services' },
    { label: 'Industrial Automation' },
    { label: 'Information Services' },
    { label: 'Information Technology / IT' },
    { label: 'Insurance' },
    { label: 'International Affairs' },
    { label: 'International Trade / Development' },
    { label: 'Internet' },
    { label: 'Investment Banking / Venture' },
    { label: 'Investment Management / Hedge Fund / Private Equity' },
    { label: 'Judiciary' },
    { label: 'Law Enforcement' },
    { label: 'Law Practice / Law Firms' },
    { label: 'Legal Services' },
    { label: 'Legislative Office' },
    { label: 'Leisure / Travel' },
    { label: 'Library' },
    { label: 'Logistics / Procurement' },
    { label: 'Luxury Goods / Jewelry' },
    { label: 'Machinery' },
    { label: 'Management Consulting' },
    { label: 'Maritime' },
    { label: 'Market Research' },
    { label: 'Marketing / Advertising / Sales' },
    { label: 'Mechanical or Industrial Engineering' },
    { label: 'Media Production' },
    { label: 'Medical Equipment' },
    { label: 'Medical Practice' },
    { label: 'Mental Health Care' },
    { label: 'Military Industry' },
    { label: 'Mining / Metals' },
    { label: 'Motion Pictures / Film' },
    { label: 'Museums / Institutions' },
    { label: 'Music' },
    { label: 'Nanotechnology' },
    { label: 'Newspapers / Journalism' },
    { label: 'Non - Profit / Volunteering' },
    { label: 'Oil / Energy / Solar / Greentech' },
    { label: 'Online Publishing' },
    { label: 'Other Industry' },
    { label: 'Outsourcing / Offshoring' },
    { label: 'Package / Freight Delivery' },
    { label: 'Packaging / Containers' },
    { label: 'Paper / Forest Products' },
    { label: 'Performing Arts' },
    { label: 'Pharmaceuticals' },
    { label: 'Philanthropy' },
    { label: 'Photography' },
    { label: 'Plastics' },
    { label: 'Political Organization' },
    { label: 'Primary / Secondary Education' },
    { label: 'Printing' },
    { label: 'Professional Training' },
    { label: 'Program Development' },
    { label: 'Public Relations / PR' },
    { label: 'Public Safety' },
    { label: 'Publishing Industry' },
    { label: 'Railroad Manufacture' },
    { label: 'Ranching' },
    { label: 'Real Estate / Mortgage' },
    { label: 'Recreational Facilities / Services' },
    { label: 'Religious Institutions' },
    { label: 'Renewables / Environment' },
    { label: 'Research Industry' },
    { label: 'Restaurants' },
    { label: 'Retail Industry' },
    { label: 'Security / Investigations' },
    { label: 'Semiconductors' },
    { label: 'Shipbuilding' },
    { label: 'Sporting Goods' },
    { label: 'Sports' },
    { label: 'Staffing / Recruiting' },
    { label: 'Supermarkets' },
    { label: 'Telecommunications' },
    { label: 'Textiles' },
    { label: 'Think Tanks' },
    { label: 'Tobacco' },
    { label: 'Translation / Localization' },
    { label: 'Transportation' },
    { label: 'Utilities' },
    { label: 'Venture Capital / VC' },
    { label: 'Veterinary' },
    { label: 'Warehousing' },
    { label: 'Wholesale' },
    { label: 'Wine / Spirits' },
    { label: 'Wireless' },
    { label: 'Writing / Editing' },
]

export const countries = [

    { label: 'Afghanistan' },
    { label: 'Albania' },
    { label: 'Algeria' },
    { label: 'Andorra' },
    { label: 'Angola' },
    { label: 'Antigua and Barbuda' },
    { label: 'Argentina' },
    { label: 'Armenia' },
    { label: 'Australia' },
    { label: 'Austria' },
    { label: 'Azerbaijan' },
    { label: 'The Bahamas' },
    { label: 'Bahrain' },
    { label: 'Bangladesh' },
    { label: 'Barbados' },
    { label: 'Belarus' },
    { label: 'Belgium' },
    { label: 'Belize' },
    { label: 'Benin' },
    { label: 'Bhutan' },
    { label: 'Bolivia' },
    { label: 'Bosnia and Herzegovina' },
    { label: 'Botswana' },
    { label: 'Brazil' },
    { label: 'Brunei' },
    { label: 'Bulgaria' },
    { label: 'Burkina Faso' },
    { label: 'Burundi' },
    { label: 'Cabo Verde' },
    { label: 'Cambodia' },
    { label: 'Cameroon' },
    { label: 'Canada' },
    { label: 'Central African Republic' },
    { label: 'Chad' },
    { label: 'Chile' },
    { label: 'China' },
    { label: 'Colombia' },
    { label: 'Comoros' },
    { label: 'Congo, Democratic Republic of the' },
    { label: 'Congo, Republic of the' },
    { label: 'Costa Rica' },
    { label: 'Côte d’Ivoire' },
    { label: 'Croatia' },
    { label: 'Cuba' },
    { label: 'Cyprus' },
    { label: 'Czech Republic' },
    { label: 'Denmark' },
    { label: 'Djibouti' },
    { label: 'Dominica' },
    { label: 'Dominican Republic' },
    { label: 'East Timor (Timor-Leste)' },
    { label: 'Ecuador' },
    { label: 'Egypt' },
    { label: 'El Salvador' },
    { label: 'Equatorial Guinea' },
    { label: 'Eritrea' },
    { label: 'Estonia' },
    { label: 'Eswatini' },
    { label: 'Ethiopia' },
    { label: 'Fiji' },
    { label: 'Finland' },
    { label: 'France' },
    { label: 'Gabon' },
    { label: 'The Gambia' },
    { label: 'Georgia' },
    { label: 'Germany' },
    { label: 'Ghana' },
    { label: 'Greece' },
    { label: 'Grenada' },
    { label: 'Guatemala' },
    { label: 'Guinea' },
    { label: 'Guinea-Bissau' },
    { label: 'Guyana' },
    { label: 'Haiti' },
    { label: 'Honduras' },
    { label: 'Hungary' },
    { label: 'Iceland' },
    { label: 'India' },
    { label: 'Indonesia' },
    { label: 'Iran' },
    { label: 'Iraq' },
    { label: 'Ireland' },
    { label: 'Israel' },
    { label: 'Italy' },
    { label: 'Jamaica' },
    { label: 'Japan' },
    { label: 'Jordan' },
    { label: 'Kazakhstan' },
    { label: 'Kenya' },
    { label: 'Kiribati' },
    { label: 'Korea, North' },
    { label: 'Korea, South' },
    { label: 'Kosovo' },
    { label: 'Kuwait' },
    { label: 'Kyrgyzstan' },
    { label: 'Laos' },
    { label: 'Latvia' },
    { label: 'Lebanon' },
    { label: 'Lesotho' },
    { label: 'Liberia' },
    { label: 'Libya' },
    { label: 'Liechtenstein' },
    { label: 'Lithuania' },
    { label: 'Luxembourg' },
    { label: 'Madagascar' },
    { label: 'Malawi' },
    { label: 'Malaysia' },
    { label: 'Maldives' },
    { label: 'Mali' },
    { label: 'Malta' },
    { label: 'Marshall Islands' },
    { label: 'Mauritania' },
    { label: 'Mauritius' },
    { label: 'Mexico' },
    { label: 'Micronesia, Federated States of' },
    { label: 'Moldova' },
    { label: 'Monaco' },
    { label: 'Mongolia' },
    { label: 'Montenegro' },
    { label: 'Morocco' },
    { label: 'Mozambique' },
    { label: 'Myanmar (Burma)' },
    { label: 'Namibia' },
    { label: 'Nauru' },
    { label: 'Nepal' },
    { label: 'Netherlands' },
    { label: 'New Zealand' },
    { label: 'Nicaragua' },
    { label: 'Niger' },
    { label: 'Nigeria' },
    { label: 'North Macedonia' },
    { label: 'Norway' },
    { label: 'Oman' },
    { label: 'Pakistan' },
    { label: 'Palau' },
    { label: 'Panama' },
    { label: 'Papua New Guinea' },
    { label: 'Paraguay' },
    { label: 'Peru' },
    { label: 'Philippines' },
    { label: 'Poland' },
    { label: 'Portugal' },
    { label: 'Qatar' },
    { label: 'Romania' },
    { label: 'Russia' },
    { label: 'Rwanda' },
    { label: 'Saint Kitts and Nevis' },
    { label: 'Saint Lucia' },
    { label: 'Saint Vincent and the Grenadines' },
    { label: 'Samoa' },
    { label: 'San Marino' },
    { label: 'Sao Tome and Principe' },
    { label: 'Saudi Arabia' },
    { label: 'Senegal' },
    { label: 'Serbia' },
    { label: 'Seychelles' },
    { label: 'Sierra Leone' },
    { label: 'Singapore' },
    { label: 'Slovakia' },
    { label: 'Slovenia' },
    { label: 'Solomon Islands' },
    { label: 'Somalia' },
    { label: 'South Africa' },
    { label: 'Spain' },
    { label: 'Sri Lanka' },
    { label: 'Sudan' },
    { label: 'Sudan, South' },
    { label: 'Suriname' },
    { label: 'Sweden' },
    { label: 'Switzerland' },
    { label: 'Syria' },
    { label: 'Taiwan' },
    { label: 'Tajikistan' },
    { label: 'Tanzania' },
    { label: 'Thailand' },
    { label: 'Togo' },
    { label: 'Tonga' },
    { label: 'Trinidad and Tobago' },
    { label: 'Tunisia' },
    { label: 'Turkey' },
    { label: 'Turkmenistan' },
    { label: 'Tuvalu' },
    { label: 'Uganda' },
    { label: 'Ukraine' },
    { label: 'United Arab Emirates' },
    { label: 'United Kingdom' },
    { label: 'United States' },
    { label: 'Uruguay' },
    { label: 'Uzbekistan' },
    { label: 'Vanuatu' },
    { label: 'Vatican City' },
    { label: 'Venezuela' },
    { label: 'Vietnam' },
    { label: 'Yemen' },
    { label: 'Zambia' },
    { label: 'Zimbabwe' },
]